// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Url struct {
	ID          int64
	Code        string
	OriginalUrl string
	Counter     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
