// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"
	"time"
)

const createUrl = `-- name: CreateUrl :exec

INSERT INTO URLS ( id, code, original_url, counter, updated_at) 
VALUES ($1,$2,$3,$4 , NOW())
`

type CreateUrlParams struct {
	ID          int64
	Code        string
	OriginalUrl string
	Counter     int64
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) error {
	_, err := q.db.ExecContext(ctx, createUrl,
		arg.ID,
		arg.Code,
		arg.OriginalUrl,
		arg.Counter,
	)
	return err
}

const getNextURLID = `-- name: GetNextURLID :one

SELECT nextval('public.urls_id_seq')
`

func (q *Queries) GetNextURLID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextURLID)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}

const getOriginalUrl = `-- name: GetOriginalUrl :one

SELECT
    original_url
FROM URLS
WHERE code = $1
`

func (q *Queries) GetOriginalUrl(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOriginalUrl, code)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const getStats = `-- name: GetStats :one

SELECT 
    original_url,
    counter,
    created_at
FROM URLS
WHERE code = $1
`

type GetStatsRow struct {
	OriginalUrl string
	Counter     int64
	CreatedAt   time.Time
}

func (q *Queries) GetStats(ctx context.Context, code string) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats, code)
	var i GetStatsRow
	err := row.Scan(&i.OriginalUrl, &i.Counter, &i.CreatedAt)
	return i, err
}

const updateCounter = `-- name: UpdateCounter :exec

UPDATE URLS
SET counter = counter + $2
WHERE code = $1
`

type UpdateCounterParams struct {
	Code    string
	Counter int64
}

func (q *Queries) UpdateCounter(ctx context.Context, arg UpdateCounterParams) error {
	_, err := q.db.ExecContext(ctx, updateCounter, arg.Code, arg.Counter)
	return err
}
